## Navigate to related symbol invoked in any place in this file
## navigates to additional-spring-configuration-metadata.json if any, or doesn't work


## properties defined in the @ConfigurationProperties classes
## initial behavior:
## Ctrl-Click navigates to setter/constructor in CP class
## back navigation is possible via class method gutter
## to usages - via the same gutter, or by Alt-F7
## now:
## Ctrl-Click shows both the setter/ctor in the @ConfigurationProperties classes and all usages
## gutter in CP class shows all usages including application.* files
my.custom.props.sp1= sp1 configured as @ConfigurationProperties class property
my.custom.props.sp2= sp2 configured as @ConfigurationProperties class property
## now:
## Ctrl-Click shows both the setter/ctor in the @ConfigurationProperties classes and all usages
## for ctor-based properties, the gutter shows only usages in application.* files
my.ctor.props.prop1= prop1 configured as @ConfigurationProperties class ctor arg
my.ctor.props.prop2= prop2 configured as @ConfigurationProperties class ctor arg

no-prefix-str-prop= string property w/o prefix

myprops.duplicated.duplicated-prop= duplicated property that exists in both same-prefix config files
myprops.duplicated.same-prefix-unique-prop1 = unique property from same-prefix config file1
myprops.duplicated.same-prefix-unique-prop2 = unique property from same-prefix config file2



## property defined in additional-spring-configuration-metadata.json only
## initial:
## Ctrl-click navigates to json
## It is impossible to navigate from json back to file or to usages
## Navigation to usages - via Alt-F7, from the Find toolwindow only
## now:
## Ctrl-click navigates to json and all usages
## It is impossible to navigate from json back to file or to usages
## the usage in additional-spring-configuration-metadata.json is shown as `name(additional.metadata.prop1)` - no source file name
additional.metadata.prop1 = property defined in json only
additional.metadata.prop2 = property defined in json only
additional.metadata.deprecated.pr1= deprecated property defined in json only

## properties defined in the application.* files only
## initial:
## Ctrl-Click navigates to all usages
## Ctrl-Click from any usage navigates back to application.*
## now:
## same behavior. Problem: the representation for property/usages differs from the one we have with
## other properties
local.prop1 = property without definition
## navigation from placeholders:
## to declarations in application.* for first one,
## to definition in CP class for second one,
## to definition in json file for third one
local.prop2 = ${local.prop1}${my.custom.props.sp1}${my.ctor.props.prop1}${additional.metadata.prop1}

## library properties.
# Ctrl-Click navigates to class
## It is impossible to navigate back (from class to properties/usages)
## Navigation to usages - via Alt-F7, from the Find toolwindow only
spring.application.name=spring boot properties usages
spring.task.execution.mode=auto
spring.profiles.default=default
spring.main.banner-mode=console