no-prefix-str-prop= profile1: string property w/o prefix

myprops.duplicated.duplicated-prop= profile1: duplicated property that exists in both same-prefix config files
myprops.duplicated.same-prefix-unique-prop1 = profile1: unique property from same-prefix config file1
myprops.duplicated.same-prefix-unique-prop2 = profile1: unique property from same-prefix config file2


my.custom.props.sp1= profile1: sp1 configured as @ConfigurationProperties class property
my.custom.props.sp2= profile1: sp2 configured as @ConfigurationProperties class property

additional.metadata.prop1 = profile1: property defined in json only

local.prop1 = profile1: property without definition
local.prop2 = profile1: ${local.prop1}${my.custom.props.sp1}${additional.metadata.prop1}